name: Build

on:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
      
      - run: cargo test

  build-linux-x86_64:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
      
      - run: cargo build --target x86_64-unknown-linux-gnu --release

  build-windows-x86_64:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
      
      - run: cargo build --target x86_64-pc-windows-msvc --release
