name: Build

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - run: cargo test

      - name: Deno CI checks
        run: deno task check-ci

  build-x86_64-unknown-linux-gnu:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - run: cargo build --target x86_64-unknown-linux-gnu --release

      - run: mv target/x86_64-unknown-linux-gnu/release/deno-plc-build target/x86_64-unknown-linux-gnu/release/deno-plc-build-x86_64-unknown-linux-gnu

      - name: Upload Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: target/x86_64-unknown-linux-gnu/release/deno-plc-build-x86_64-unknown-linux-gnu

  build-x86_64-pc-windows-msvc:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - run: cargo build --target x86_64-pc-windows-msvc --release

      - run: mv target/x86_64-pc-windows-msvc/release/deno-plc-build.exe target/x86_64-pc-windows-msvc/release/deno-plc-build-x86_64-pc-windows-msvc.exe

      - name: Upload Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: target/x86_64-pc-windows-msvc/release/deno-plc-build-x86_64-pc-windows-msvc.exe
    
  publish-jsr:
    runs-on: ubuntu-latest
    needs: 
      - build-x86_64-unknown-linux-gnu
      - build-x86_64-pc-windows-msvc
      - test

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Publish JSR
        run: deno publish

      